package com.pudim.flan.repos;

import com.pudim.flan.model.myfolder.Tabela1;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Repository
public interface Tabela1Repository
    extends JpaRepository<Tabela1, Long>, JpaSpecificationExecutor<Tabela1> {}
