package com.batatas.frango.repos;

import com.batatas.frango.model.TabelOne;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Repository
public interface TabelOneRepository
    extends JpaRepository<TabelOne, Long>, JpaSpecificationExecutor<TabelOne> {}
