package com.artsoft.gitintegration.repos;

import com.artsoft.gitintegration.model.folderfortablesandenums.Tbl1;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Repository
public interface Tbl1Repository extends JpaRepository<Tbl1, Long>, JpaSpecificationExecutor<Tbl1> {}
