package com.admin.codegenreallynew.mapper;

import com.admin.codegenreallynew.dto.somefolderx2.Tbl1ObjXdto;
import com.admin.codegenreallynew.model.somefolder.Tbl1;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Component
@Mapper
public abstract class Tbl1ObjXReadMapper extends EntityMapper {

  @Mapping(target = "idTable1", source = "idTbl1")
  public abstract Tbl1ObjXdto entityToDto(Tbl1 entity);

  public abstract List<Tbl1ObjXdto> entityToDto(List<Tbl1> entityList);
}
