package com.admin.codegenreallynew.mapper;

import com.admin.codegenreallynew.dto.somefolderx2.Tbl1ObjXdto;
import com.admin.codegenreallynew.model.somefolder.Tbl1;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Component
@Mapper
public abstract class Tbl1ObjXWriteMapper extends EntityMapper {

  @Mapping(target = "idTbl1", source = "idTable1")
  public abstract Tbl1 dtoToEntity(Tbl1ObjXdto dto);

  public abstract List<Tbl1> dtoToEntity(List<Tbl1ObjXdto> dtoList);

  @Mapping(target = "idTable1", source = "idTbl1")
  public abstract Tbl1ObjXdto entityToDto(Tbl1 entity);

  public abstract List<Tbl1ObjXdto> entityToDto(List<Tbl1> entityList);

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  @Mapping(target = "idTbl1", source = "idTable1")
  public abstract void updateFromDto(@MappingTarget Tbl1 entity, Tbl1ObjXdto dto);
}
