package com.admin.codegenreallynew.mapper;

import com.admin.codegenreallynew.dto.somefolderx2.Tbl1ObjXdto;
import com.admin.codegenreallynew.model.somefolder.Tbl1;
import com.admin.codegenreallynew.schema.Tbl1ObjXSchema;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Component
@Mapper
public interface Tbl1ObjXMapper {

  @Mapping(target = "idTbl1", source = "idTable1")
  Tbl1 dtoToEntity(Tbl1ObjXdto dto);

  List<Tbl1> dtoToEntity(List<Tbl1ObjXdto> dtoList);

  Tbl1ObjXSchema dtoToSchema(Tbl1ObjXdto dto);

  List<Tbl1ObjXSchema> dtoToSchema(List<Tbl1ObjXdto> dtoList);

  @Mapping(target = "idTable1", source = "idTbl1")
  Tbl1ObjXdto entityToDto(Tbl1 entity);

  List<Tbl1ObjXdto> entityToDto(List<Tbl1> entityList);

  Tbl1ObjXdto schemaToDto(Tbl1ObjXSchema schema);

  List<Tbl1ObjXdto> schemaToDto(List<Tbl1ObjXSchema> schemaList);

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  @Mapping(target = "idTbl1", source = "idTable1")
  void updateFromDto(@MappingTarget Tbl1 entity, Tbl1ObjXdto dto);
}
