package com.admin.codegenreallynew.mapper;

import com.admin.codegenreallynew.dto.somefolderx2.Tbl2ObjXdto;
import com.admin.codegenreallynew.model.somefolder.Tbl2Xx;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Component
@Mapper
public abstract class Tbl2ObjXReadMapper extends EntityMapper {

  @Mapping(target = "idTable2", source = "idTbl2Xx")
  public abstract Tbl2ObjXdto entityToDto(Tbl2Xx entity);

  public abstract List<Tbl2ObjXdto> entityToDto(List<Tbl2Xx> entityList);
}
