package com.admin.codegenreallynew.mapper;

import com.admin.codegenreallynew.dto.somefolderx2.Tbl2ObjXdto;
import com.admin.codegenreallynew.model.somefolder.Tbl2Xx;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Component
@Mapper
public abstract class Tbl2ObjXWriteMapper extends EntityMapper {

  @Mapping(target = "idTbl2Xx", source = "idTable2")
  public abstract Tbl2Xx dtoToEntity(Tbl2ObjXdto dto);

  public abstract List<Tbl2Xx> dtoToEntity(List<Tbl2ObjXdto> dtoList);

  @Mapping(target = "idTable2", source = "idTbl2Xx")
  public abstract Tbl2ObjXdto entityToDto(Tbl2Xx entity);

  public abstract List<Tbl2ObjXdto> entityToDto(List<Tbl2Xx> entityList);

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  @Mapping(target = "idTbl2Xx", source = "idTable2")
  public abstract void updateFromDto(@MappingTarget Tbl2Xx entity, Tbl2ObjXdto dto);
}
