package com.admin.codegenreallynew.util;

import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Filter Criteria.
 *
 * <p>Applies an operator to a column with a value, e.g. Column == 'value'.
 */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Getter
@AllArgsConstructor
public class FilterCriteria {

  private final String key;
  private final FilterOperator operator;
  private final Object value;
}
