package com.bacon.eggs.model;

import javax.annotation.processing.Generated;
import lombok.Getter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
public enum EnumTwoFinal {
  E2(0);

  EnumTwoFinal(int value) {
    this.value = value;
  }

  @Getter private final int value;

  public static EnumTwoFinal of(int value) {
    for (EnumTwoFinal v : values()) {
      if (v.value == value) {
        return v;
      }
    }
    return null;
  }
}
