package com.bacon.eggs.model;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import javax.annotation.processing.Generated;

/** Converts an EnumTwoFinal to its value and vice-versa. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Converter(autoApply = true)
public class EnumTwoFinalConverter implements AttributeConverter<EnumTwoFinal, Integer> {

  @Override
  public Integer convertToDatabaseColumn(EnumTwoFinal attribute) {
    if (attribute == null) {
      return null;
    }
    return attribute.getValue();
  }

  @Override
  public EnumTwoFinal convertToEntityAttribute(Integer dbData) {
    if (dbData == null) {
      return null;
    }
    return EnumTwoFinal.of(dbData);
  }
}
