package com.mybussiness.codegen.model.folderfortablesandenums;

import javax.annotation.processing.Generated;

/** Abstract class common to all entities. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
public abstract class AbstractEntity {}
