package com.mybussiness.codegen.model.folderfortablesandenums;

import javax.annotation.processing.Generated;
import lombok.Getter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
public enum E1 {
  E1(0);

  E1(int value) {
    this.value = value;
  }

  @Getter private final int value;

  public static E1 of(int value) {
    for (E1 v : values()) {
      if (v.value == value) {
        return v;
      }
    }
    return null;
  }
}
