package com.mybussiness.codegen.model.folderfortablesandenums;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import javax.annotation.processing.Generated;

/** Converts an E1 to its value and vice-versa. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Converter(autoApply = true)
public class E1Converter implements AttributeConverter<E1, Integer> {

  @Override
  public Integer convertToDatabaseColumn(E1 attribute) {
    if (attribute == null) {
      return null;
    }
    return attribute.getValue();
  }

  @Override
  public E1 convertToEntityAttribute(Integer dbData) {
    if (dbData == null) {
      return null;
    }
    return E1.of(dbData);
  }
}
