package com.mybussiness.codegen.model.folderfortablesandenums;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import javax.annotation.processing.Generated;

/** Converts an E2 to its value and vice-versa. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Converter(autoApply = true)
public class E2Converter implements AttributeConverter<E2, Integer> {

  @Override
  public Integer convertToDatabaseColumn(E2 attribute) {
    if (attribute == null) {
      return null;
    }
    return attribute.getValue();
  }

  @Override
  public E2 convertToEntityAttribute(Integer dbData) {
    if (dbData == null) {
      return null;
    }
    return E2.of(dbData);
  }
}
