package com.batatas.frango.model.newfolder;

import javax.annotation.processing.Generated;
import lombok.Getter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
public enum EnumTwo {
  E2(0);

  EnumTwo(int value) {
    this.value = value;
  }

  @Getter private final int value;

  public static EnumTwo of(int value) {
    for (EnumTwo v : values()) {
      if (v.value == value) {
        return v;
      }
    }
    return null;
  }
}
