package com.batatas.frango.model.newfolder;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import javax.annotation.processing.Generated;

/** Converts an EnumTwo to its value and vice-versa. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Converter(autoApply = true)
public class EnumTwoConverter implements AttributeConverter<EnumTwo, Integer> {

  @Override
  public Integer convertToDatabaseColumn(EnumTwo attribute) {
    if (attribute == null) {
      return null;
    }
    return attribute.getValue();
  }

  @Override
  public EnumTwo convertToEntityAttribute(Integer dbData) {
    if (dbData == null) {
      return null;
    }
    return EnumTwo.of(dbData);
  }
}
