package com.bacon.eggs.model.renamed;

import javax.annotation.processing.Generated;
import lombok.Getter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
public enum EnumOneFinal {
  E1(0);

  EnumOneFinal(int value) {
    this.value = value;
  }

  @Getter private final int value;

  public static EnumOneFinal of(int value) {
    for (EnumOneFinal v : values()) {
      if (v.value == value) {
        return v;
      }
    }
    return null;
  }
}
