package com.admin.codegenreallynew.dto.somefolderx2;

import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Tbl1ObjXdto {

  @EqualsAndHashCode.Include protected Long idTable1;
}
