package com.admin.codegenreallynew.model.somefolder;

import javax.annotation.processing.Generated;
import lombok.Getter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
public enum E1X {
  E1(0);

  E1X(int value) {
    this.value = value;
  }

  @Getter private final int value;

  public static E1X of(int value) {
    for (E1X v : values()) {
      if (v.value == value) {
        return v;
      }
    }
    return null;
  }
}
