package com.admin.codegenreallynew.model.somefolder;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import javax.annotation.processing.Generated;

/** Converts an E1X to its value and vice-versa. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Converter(autoApply = true)
public class E1XConverter implements AttributeConverter<E1X, Integer> {

  @Override
  public Integer convertToDatabaseColumn(E1X attribute) {
    if (attribute == null) {
      return null;
    }
    return attribute.getValue();
  }

  @Override
  public E1X convertToEntityAttribute(Integer dbData) {
    if (dbData == null) {
      return null;
    }
    return E1X.of(dbData);
  }
}
