package com.admin.codegenreallynew.model.somefolder;

import javax.annotation.processing.Generated;
import lombok.Getter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
public enum E2X {
  E2(0);

  E2X(int value) {
    this.value = value;
  }

  @Getter private final int value;

  public static E2X of(int value) {
    for (E2X v : values()) {
      if (v.value == value) {
        return v;
      }
    }
    return null;
  }
}
