package com.admin.codegenreallynew.model.somefolder;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import javax.annotation.processing.Generated;

/** Converts an E2X to its value and vice-versa. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Converter(autoApply = true)
public class E2XConverter implements AttributeConverter<E2X, Integer> {

  @Override
  public Integer convertToDatabaseColumn(E2X attribute) {
    if (attribute == null) {
      return null;
    }
    return attribute.getValue();
  }

  @Override
  public E2X convertToEntityAttribute(Integer dbData) {
    if (dbData == null) {
      return null;
    }
    return E2X.of(dbData);
  }
}
