package com.artsoft.gitintegration.model.folderfortablesandenums;

import javax.annotation.processing.Generated;
import lombok.Getter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
public enum E2 {
  E2(0);

  E2(int value) {
    this.value = value;
  }

  @Getter private final int value;

  public static E2 of(int value) {
    for (E2 v : values()) {
      if (v.value == value) {
        return v;
      }
    }
    return null;
  }
}
