package com.pudim.flan.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import javax.annotation.processing.Generated;
import lombok.Data;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Data
@Entity
@Table
public class Tabela2 extends AbstractEntity {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  protected Long idTabela2;
}
