package com.batatas.frango.model.renamed;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import javax.annotation.processing.Generated;

/** Converts an EnumOne to its value and vice-versa. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Converter(autoApply = true)
public class EnumOneConverter implements AttributeConverter<EnumOne, Integer> {

  @Override
  public Integer convertToDatabaseColumn(EnumOne attribute) {
    if (attribute == null) {
      return null;
    }
    return attribute.getValue();
  }

  @Override
  public EnumOne convertToEntityAttribute(Integer dbData) {
    if (dbData == null) {
      return null;
    }
    return EnumOne.of(dbData);
  }
}
