package com.batatas.frango.model.renamed;

import javax.annotation.processing.Generated;
import lombok.Getter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
public enum EnumOne {
  E1(0);

  EnumOne(int value) {
    this.value = value;
  }

  @Getter private final int value;

  public static EnumOne of(int value) {
    for (EnumOne v : values()) {
      if (v.value == value) {
        return v;
      }
    }
    return null;
  }
}
