package com.pudim.flan;

import javax.annotation.processing.Generated;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@SpringBootTest
class MainTests {

  @Test
  void contextLoads() {}
}
