package com.pudim.flan.model.myfolder;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import javax.annotation.processing.Generated;

/** Converts an Enum1 to its value and vice-versa. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Converter(autoApply = true)
public class Enum1Converter implements AttributeConverter<Enum1, Integer> {

  @Override
  public Integer convertToDatabaseColumn(Enum1 attribute) {
    if (attribute == null) {
      return null;
    }
    return attribute.getValue();
  }

  @Override
  public Enum1 convertToEntityAttribute(Integer dbData) {
    if (dbData == null) {
      return null;
    }
    return Enum1.of(dbData);
  }
}
