package com.admin.codegenreallynew.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Getter
@Setter
@AllArgsConstructor
public class Tbl2ObjXSchema {

  @JsonProperty(access = Access.READ_ONLY)
  protected Long idTable2;
}
