package com.arroz.doce.model;

import javax.annotation.processing.Generated;
import lombok.Getter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
public enum Enum2 {
  E2(0);

  Enum2(int value) {
    this.value = value;
  }

  @Getter private final int value;

  public static Enum2 of(int value) {
    for (Enum2 v : values()) {
      if (v.value == value) {
        return v;
      }
    }
    return null;
  }
}
