package com.arroz.doce.model;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import javax.annotation.processing.Generated;

/** Converts an Enum2 to its value and vice-versa. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Converter(autoApply = true)
public class Enum2Converter implements AttributeConverter<Enum2, Integer> {

  @Override
  public Integer convertToDatabaseColumn(Enum2 attribute) {
    if (attribute == null) {
      return null;
    }
    return attribute.getValue();
  }

  @Override
  public Enum2 convertToEntityAttribute(Integer dbData) {
    if (dbData == null) {
      return null;
    }
    return Enum2.of(dbData);
  }
}
