package com.bacon.eggs.repos;

import com.bacon.eggs.model.TabelTwoFinal;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding")
@Repository
public interface TabelTwoFinalRepository
    extends JpaRepository<TabelTwoFinal, Long>, JpaSpecificationExecutor<TabelTwoFinal> {}
